services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/var/www
    networks:
      - market-core-api_network 

  web: 
    image: nginx:stable-alpine3.20-perl
    ports:
      - "8010:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - market-core-api_network 

  db:
    image: postgres:13.21-alpine3.22
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - market-core-api_network 

networks:
  market-core-api_network:
    driver: bridge
